version: "3.8"

services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - db
        volumes:
            - ./src:/var/www/html/
        ports: 
            - 8000:80

    memcached:
        image: bitnami/memcached:latest
        environment:
            - MEMCACHED_USERNAME=my_user
            - MEMCACHED_PASSWORD=my_password
            - MEMCACHED_CACHE_SIZE=128
            - MEMCACHED_MAX_CONNECTIONS=2000
            - MEMCACHED_THREADS=4
            - MEMCACHED_MAX_ITEM_SIZE=8388608
        ports:
            - 11211:11211
        networks:
            - app-tier

    apache:
        image: httpd:2.4
        ports:
            - 80:80
        volumes:
            - ./src:/usr/local/apache2/htdocs
        networks:
            - app-tier
            
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app_db
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
        ports:
            - 3306:3306
        #networks:
        #    - app-tier

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dev_pma
        links:
            - db
        ports:
            - 8183:80
        restart: always
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        networks:
            - app-tier
        depends_on:
            - db

networks:
    app-tier:
        driver: bridge
